# Assignment 3

## Written by Mizanur Rahman

### Problem 1

 
Write a function called countUnique that has one parameter which is a NumPy array. The array will be a list of integers with many repeated values. The function should count how many times each unique integer appears and return the counts. For example, if it is given the array array([3, 3, 3, 1, 1, 3, 1, 1, 3, 2]), it should return the counts [(1, 4), (2, 1), (3, 5)] since 1 appears 4 times, 2 appears once, and 3 appears 5 times.

In a separate code cell, create an create a NumPy array of 20 random integers from 1 to 20. Use your countUnique to determine how many times each number appears.

In a separate code cell, create an create a NumPy array of 10,000 random integers from 1 to 5. Use your countUnique to determine how many times each number appears.


In [1]:
import numpy as np

In [2]:
NumPy = [3, 3, 3, 1, 1, 3, 1, 1, 3, 2]
def countUnique(NumPy):
    
    result = []

    NumPy.sort() # SORTING the array

    index = 0

    while index < len(NumPy):

    # below is for occurrence of each number

        one = NumPy[index]

        count = 0

        while index < len(NumPy) and one == NumPy[index]:

            count += 1
            index += 1

        # putting a tuple of number and it's frequency

        result.append((one, count))

    return result

print('A list of integers with many repeated values:', countUnique(NumPy))
        
    

A list of integers with many repeated values: [(1, 4), (2, 1), (3, 5)]


In [3]:

first = np.random.randint(1, 20, size=20)
print('A NumPy array of 20 random integers from 1 to 20:', countUnique(first))

A NumPy array of 20 random integers from 1 to 20: [(1, 2), (2, 1), (4, 1), (5, 2), (6, 2), (8, 1), (9, 3), (11, 1), (12, 1), (16, 1), (17, 3), (18, 1), (19, 1)]


In [4]:
second = np.random.randint(1, 5, size = 10000)
print('A NumPy array of 10,000 random integers from 1 to 5:', countUnique(second))

A NumPy array of 10,000 random integers from 1 to 5: [(1, 2520), (2, 2590), (3, 2444), (4, 2446)]


## Problem 2

Write a function called findNumbers that has two parameters. The first parameter, npData, is a NumPy array of integers
and the second, n, is an integer. The function should return a new array of all the values in npData that are evenly 
divisible by n. For example, if the function is give the NumPy array array([7, 4, 9, 1, 0, 6, 3, 5, 2, 8]) and the 
value 3 for n, then the function should return the NumPy array array([9 0 6 3])

In a separate code cell, create an create a array of 20 random integers from 1 to 20. Print the array, and then use your 
findNumbers to get an array that contains all the numbers evenly divisible by 4. Print the results.

In a separate code cell, create an create a array of 250 random integers from 1 to 1000. Print the array, and then use your
findNumbers to get an array that contains all the numbers evenly divisible by 10. Print the results.


In [6]:
def findNumbers(npData,n):              #function to check divisibility
    new_list=[]
    for element in npData:
        if (element % n==0):
            new_list.append(element)
    nump = np.array(new_list)
    return nump

In [8]:
#An array of 20 random integers from 1 to 20.

new_array1 = np.random.randint(20,size=20)           # for random numbers
print("numpy array:",new_array1)
print("divisible array:",findNumbers(new_array1,4))     #find divisibles of 4


numpy array: [ 6  5  3 16  9  8 10  2 12  3  9 17  2 16 13 13 10 14 16 10]
divisible array: [16  8 12 16 16]


In [9]:
#an array of 250 random integers from 1 to 1000
new_array2 = np.random.randint(1000,size=250)
print("numpy_array:",new_array2)
print("divisible array:",findNumbers(new_array2,10))       #for divisibles of 10

numpy_array: [371 763  89 666 411  33 389 888 906 203 332 414 412 372 414 409 353 969
 477 295 711 125 763 166 999 236 699 257 663 601 889 687 843 510 980 544
 743 537 405 234 866 233 876 417 378 399 670 121 196 499 730 644 171 647
 811 214 148 967 341  35 972 663 947 473 189 474   8 516 248 942 576 821
 690 246 768 110 172 636 227 708 598 774 677 932 685 184  57 143 985 530
 390 971 819 686 728 786 379 560 609 394 180 984 932 361 837 653 406 592
 223   8 608 760 208 766 589 498 845 709 776 573 416 270 989 607 193 158
 618 960  53 802 721 719  11  94 320 223 257 125 981 481 655 256  22 905
 615 865 603 374 864 883 107 777  38 736 255 803 964 536 573 282 826 604
 373 570 748 720 643  67 369  95 892 482 442 427 576 990 168 746 471 557
 147 941 903 778 905   4 794 103 145 690 711 616 726 394 175 428 495 754
 287 267 400 185 964 130 192 154 884 493 623 892 578 606 660 578 162 248
 706 103 996 949  41  17 267 173 680 549 464 762 259 579 512 834 412 782
 382 559 546  79 358 766 252 334 737 6

### Problem 3

Research how to use NumPy's loadtxt() function. Once you understand it, use it to read the values in the file numbers.txt into a NumPy array. The file has one integer per line. Once you have it in memory, use it to output the following information:

    The number of values in the file
    The smallest value in the file
    The largest value in the file
    The average of all the values
    The standard deviation of all the values

In [10]:
x = np.loadtxt('numbers.txt')

In [11]:
print(x)

[681424. 427603. 113386. ... 836135.  81177. 777216.]


In [12]:
print('The number of values in the file is:', np.size(x))

The number of values in the file is: 10000


In [13]:
print('The smallest value in the file is:', np.min(x))

The smallest value in the file is: 81.0


In [14]:
print('The largest value in the file is:', np.max(x))

The largest value in the file is: 999989.0


In [18]:
#np.argmin(x)+1

In [19]:
#np.argmax(x)+1

In [20]:
print('The average of all the values:', np.mean(x))

The average of all the values: 502164.309


In [21]:
print('The standard deviation of all the values:', np.std(x))

The standard deviation of all the values: 289261.0973415335


### Problem 4

Use loadtxt() to read the file values.txt. This file has three integers per line. When you read it, it should create a two-dimensional array. Once you have the data in memory, use it to output the following information:

    The number of lines in the file
    The number of values in the file
    The number of lines that contain the value 0
    The largest value on each line
    The number of rows where at least one value is repeated, e.g. [42, 3, 42] contains the repeated value 42

In [22]:
data2d = np.loadtxt('values.txt')

In [23]:
print('Contents of 2D Numpy Array:', data2d, sep='\n')

Contents of 2D Numpy Array:
[[ 12.  78.  52.]
 [ 26.  47.  11.]
 [ 76.  20.  64.]
 [ 35.  70.  92.]
 [ 55.  92.  62.]
 [ 85.  90.  60.]
 [ 84.  21.  73.]
 [  4.  62.  18.]
 [  9.  92.   7.]
 [ 24.  52.  77.]
 [  5.  60.  78.]
 [ 10.  43.  91.]
 [  4.  52.  82.]
 [ 73.  44.  86.]
 [ 18.  91.  80.]
 [ 54.  91.  27.]
 [ 67.  67.  23.]
 [ 19.  43.  48.]
 [ 72.  53.  24.]
 [ 17.  77.  91.]
 [ 85.  43.  29.]
 [ 64.  54.  82.]
 [ 60.  24.  65.]
 [ 89.  37.  44.]
 [ 88.  30.  13.]
 [ 62.  75.  49.]
 [ 83.   9.  87.]
 [ 28.  22.  12.]
 [ 25.  27.  22.]
 [ 10.  21.   1.]
 [ 93.  11.  49.]
 [ 48.  98.  40.]
 [ 70.  37.  34.]
 [ 71.  40.  83.]
 [ 57.  92.  29.]
 [ 15.  87.  80.]
 [ 95.  95.  23.]
 [ 21.  36.  83.]
 [ 41.  43.  95.]
 [  3.  52.  12.]
 [ 55. 100.  57.]
 [ 71.   4.  92.]
 [ 57.  34.  57.]
 [ 29.  65.   5.]
 [ 17.  86.  74.]
 [ 31.  98.  78.]
 [ 60.  96.  37.]
 [ 22.  34.  53.]
 [ 30.  30.   9.]
 [ 34.  52.  39.]
 [ 37.  61.  50.]
 [ 43.  16.  18.]
 [ 57.  34.  56.]
 [ 83.  35.  55.]


In [24]:
print('The number of lines in a 2d data is:')
count = 0
for lines in data2d:
    #if lines.strip():
        count +=1
print(count)

The number of lines in a 2d data is:
200


In [25]:
print('The number of values in the file:', np.prod(data2d.shape))

The number of values in the file: 600


In [26]:
print('The number of lines that contain the value 0 with index number is:')
np.argwhere(data2d == 0) + 1

The number of lines that contain the value 0 with index number is:


array([[ 72,   2],
       [118,   1],
       [166,   2]], dtype=int64)

In [27]:
maxInRows = np.amax(data2d, axis=1)
 
print('The largest value on each line: ', maxInRows, sep='\n')

The largest value on each line: 
[ 78.  47.  76.  92.  92.  90.  84.  62.  92.  77.  78.  91.  82.  86.
  91.  91.  67.  48.  72.  91.  85.  82.  65.  89.  88.  75.  87.  28.
  27.  21.  93.  98.  70.  83.  92.  87.  95.  83.  95.  52. 100.  92.
  57.  65.  86.  98.  96.  53.  30.  52.  61.  43.  57.  83.  48.  93.
  66. 100.  84.  87.  50.  54.  39.  66.  84.  89.  94.  92.  83.  71.
  70.  33.  39.  92.  68.  58.  55.  67.  97.  94.  87.  44.  77.  82.
  66.  93.  78.  60.  73.  86.  70.  69.  94.  98.  61.  81.  56.  34.
  67.  96.  75.  63.  92.  61.  39.  61.  94.  81.  83.  91.  93.  16.
  33.  64.  91.  53.  73.  58.  75.  54.  54.  87.  95.  67.  41.  75.
  67.  89.  73.  85.  84.  70.  56. 100.  69.  86.  42.  83.  62.  58.
  70.  45.  77.  75.  88.  52.  70.  68.  16.  99. 100.  89.  96.  93.
  68.  68.  76.  70.  85.  91.  78.  59.  55.  73.  97.  99.  66.  98.
  60.  85.  63.  45. 100.  54.  97.  97.  62.  68.  90.  32.  91.  56.
  89.  74.  85.  95.  71.  75.  93.  90.  32

In [28]:
nofr=0
for row in data2d:
    for value in row:
        if row[0]==row[1] or row[0]==row[2] or row[1]==row[2] or row[0]==row[1]==row[2]:
            nofr+=1
print('The number of rows where at least one value is repeated:', nofr) 

The number of rows where at least one value is repeated: 27


## Problem 5

    Use loadtxt() to read the file words.txt. This file has one word per line. The words are all lowercase and there are no punctuation characters - only letters

    NumPy arrays can hold strings too. There is one caveat to strings: when NumPy reads strings it sets a max length for the column. The default is 31. The reason for this is that it makes NumPy more efficient in memory. You can change the max length by setting the data type for loadtxt() to dtype='U50'. This says that the strings can now be up to 50 characters. Once you have the data in memory, use it to do the following:
        Sort it and write all the words out to the text file named sortedWords.txt. Make sure you can open the file in a text editor and view the contents.
        For each letter, find the longest word. That is find the longest word that starts with a, and then the longest word that starts with b, and so on.

Ensure that all output is labeled descriptively. It should be obvious what each value means. 

In [29]:
data3 = np.loadtxt('words.txt', dtype='U50')
#data3 = np.loadtxt('words.txt', delimiter=chr(164),comments="#",dtype='U50')

In [30]:
data3

array(['exoccipital', 'unobsceneness', 'polyaxonic', ..., 'overstraight',
       'flute', 'predefective'], dtype='<U50')

In [31]:
data4=np.sort(data3, axis = None)

In [32]:
#Sort it and write all the words out to the text file named sortedWords.txt.
np.savetxt('sortedWords.txt', data4, fmt='%s')

In [33]:
print('The longest word that starts with a, and then the longest word that starts with b, and so on:')
alphabets=['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
for letter in alphabets:
    let=[]
    wds=[]
    for data in data4:
        if letter==data[0]:
            lend=len(data)
            let.append(lend)
            wds.append(data)          
    maxl=max(let)
    ind=let.index(maxl)
    lng=wds[ind]

    print()
    print(letter,lng)
            
            
    

The longest word that starts with a, and then the longest word that starts with b, and so on:

a antidisestablishmentarianism

b blepharosphincterectomy

c cyclotrimethylenetrinitramine

d dichlorodiphenyltrichloroethane

e electroencephalographically

f formaldehydesulphoxylate

g gastroenteroanastomosis

h hydroxydehydrocorticosterone

i immunoelectrophoretically

j jurisprudentialist

k keratoconjunctivitis

l laparocolpohysterotomy

m microspectrophotometrically

n naphthylaminesulphonic

o overindividualistically

p pneumonoultramicroscopicsilicovolcanoconiosis

q quattuordecillionth

r representationalistic

s superincomprehensibleness

t trinitrophenylmethylnitramine

u ultranationalistically

v vagoglossopharyngeal

w westnorthwestwardly

x xanthocreatinine

y yohimbinization

z zoologicoarchaeologist
